# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pyicloud/services/reminders/protobuf/reminders.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "pyicloud/services/reminders/protobuf/reminders.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n4pyicloud/services/reminders/protobuf/reminders.proto\x12$pyicloud.services.reminders.protobuf"K\n\rTitleDocument\x12:\n\x05title\x18\x02 \x01(\x0b\x32+.pyicloud.services.reminders.protobuf.Title"L\n\x05Title\x12\x43\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x32.pyicloud.services.reminders.protobuf.TitleContent"\x1c\n\x0cTitleContent\x12\x0c\n\x04text\x18\x02 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "pyicloud.services.reminders.protobuf.reminders_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TITLEDOCUMENT"]._serialized_start = 94
    _globals["_TITLEDOCUMENT"]._serialized_end = 169
    _globals["_TITLE"]._serialized_start = 171
    _globals["_TITLE"]._serialized_end = 247
    _globals["_TITLECONTENT"]._serialized_start = 249
    _globals["_TITLECONTENT"]._serialized_end = 277
# @@protoc_insertion_point(module_scope)
