name: Linting
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install the requested Python (still needed for Ruff/isort binaries)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Install the uv CLI and add it to PATH
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          enable-cache: true

      # Create .venv from the lockfile (dev group installs linter/formatter)
      - name: Sync dependencies
        run: uv sync --locked --group dev

      - name: isort (check only)
        run: uv run isort --recursive --diff .

      - name: Ruff Linter
        run: uv run ruff check .

      - name: Ruff Formatter (check)
        run: uv run ruff format --check .
