name: Linting
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Python for Ruff/isort binaries
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # 2) Install uv CLI (puts uv + tool wrappers on PATH)
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: '0.6.17'
          enable-cache: true        # speeds up repeated runs

      # 3) Bring in the dev dependencies (ruff, isort, etc.)
      - name: Sync dependencies
        run: uv sync --locked --group dev

      # ───────---- NEW STEPS start here -----─────────────
      - name: Install pre-commit (patched)
        run: uv tool install pre-commit --with pre-commit-uv

      - name: Run all pre-commit hooks
        run: pre-commit run --all-files -v
