name: Tests

on: [workflow_dispatch, push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: '0.6.17'
          enable-cache: true

      - name: Sync project (dev group)
        run: uv sync --locked --group dev

      - name: Install tox CLI (with plugin)
        run: uv tool install tox --with tox-uv

      - name: Run tox matrix
        run: uv run tox

  coverage:
    name: Generate Coverage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v1
        with:
          version: '0.6.17'
          enable-cache: true

      - name: Sync project (dev group)
        run: uv sync --locked --group dev

      - name: Generate coverage
        run: uv run pytest --cov=. --cov-config=.coveragerc --cov-report xml:coverage.xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.xml

  compatibility:
    name: Compatibility Test (Python 3.9)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: '0.6.17'
          enable-cache: true

      - name: Sync dependencies for Python 3.9
        run: uv sync --locked --python-version 3.9 --group dev

      - name: Run basic tests
        run: uv run pytest -xvs tests/test_base.py
